routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::get('/hello/{nama?}',function($nama='default'){
    return view('hello',array('nama'=>$nama));
    //return view('hello')->with('nama',$nama);
});*/


Route::get('/hello/{nama?}','HelloController@index');
Route::get('/show','HelloController@show');
Route::post('/tampil','HelloController@HitungLuas')->name('tampil');

//routing database
Route::get('db', function () {
    //return DB::select('select * from todo_lists');
    //$todo_lists = DB::table('todo_lists')->orderBy('name')->get();
    //return json_encode($todo_lists);
    //$user = DB::table('todo_lists')->where('id',1)->first();
    //return json_encode($user);

    //DB::insert('insert into users (id, name) values (?, ?)', [1, 'Dayle'])
    //DB::table('todo_lists')->insert([["name"=>"Belajar Eloquent"]]);
    //DB::table('todo_lists')->where('id',1)->update(["name"=>"Belajar Update"]);
    DB::table('todo_lists')->where('id',1)->delete();
    return DB::table('todo_lists')->get();
});

Route::resource('todos', 'TodoListController');
Route::resource('products', 'ProductController'); 
/*Route::get('/sample',function(){
    $data = ['nama'=>'Erick Kurniawan','alamat'=>'jogja'];
    return view('hello')->with($data);
});*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/todos/create.blade.php
@extends('layouts.main')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="#">Home</a>
    </li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('content')
<div class="col-md-12">
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{ route('todos.store') }}">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="name">Name :</label>
            <input type="text" name="name" class="form-control" />
        </div>
        <button type="submit" class="btn btn-info btn-sm">Add</button>
    </form>
</div>

@endsection

resources/views/todos/edit.blade.php
@extends('layouts.main')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="#">Home</a>
    </li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('content')

<div class="col-md-12">
    <form method="POST" action="{{ route('todos.update',['id'=>$list->id]) }}">
        {{ method_field('PUT') }}
        {{ csrf_field() }}
        <div class="form-group">
            <label for="name">Name :</label>
            <input type="text" name="name" value="{{ $list->name }}" class="form-control" />
        </div>
        <button type="submit" class="btn btn-info btn-sm">Update</button>
    </form>
</div>

@endsection

resources/views/todos/index.blade.php
@extends('layouts.main')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="#">Home</a>
    </li>
    <li class="breadcrumb-item active">Todo Lists</li>
@endsection

@section('content')
<div class="col-md-12">
    <a href="{{ route('todos.create') }}" class="btn btn-info btn-sm">Add Todo</a><br>
    <h2>Daftar Todo</h2>
    <br/>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th></th>
        </tr>
        @foreach($todo_lists as $list)
            <tr>
                <td>{{ $list->id }}</td>
                <td>{{ $list->name }}</td>
               
                <td>
                @if($status==true)
                <a href="{{ route('todos.show',['id'=>$list->id]) }}" class="btn btn-success btn-sm">detail</a>
                &nbsp;
                <a href="{{ route('todos.edit',['id'=>$list->id]) }}" class="btn btn-warning btn-sm">edit</a>
                @endif
                </td>
            </tr>
        @endforeach
    </table>
</div>

@endsection

resources/views/todos/show.blade.php
@extends('layouts.main')

@section('breadcrumb')
    <li class="breadcrumb-item">
        <a href="#">Home</a>
    </li>
    <li class="breadcrumb-item active">Tampil</li>
@endsection

@section('content')
<div class="col-md-12">
    <h2>Show Data</h2>
    <p>ID : {{ $list->id }} dan Name : {{ $list->name }}</p>
</div>

@endsection